
noise_scheduler:
  num_train_timesteps: 1000
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: scaled_linear
  clip_sample: false
  prediction_type: v_prediction
  rescale_betas_zero_snr: true
  steps_offset: 1

model:
  patch_size: 2
  input_size: [40, 64]
  learn_sigma: False
  depth: 28
  hidden_size: 1152
  num_heads: 16
  use_y_embedder: False
  condition_channels: 2048      # useless here

dataset:
  data_root: /mnt/store/kmei1/projects/t1/datasets/godmodeanimation_runjump/runjump_dataset
  resolution: 256               # useless here
  video_length: 16
  dataset_name: UCF-101
  subset_split: train
  clip_step: 1
  temporal_transform: rand_clips
  cfg_random_null_text_ratio: 0.
  latent_scale: 16

ema_iter: 100
log_every: 10
warmup_steps: 200
global_batch_size: 8
learning_rate: 0.00004
